name       : qca
version    : 2.2.1
release    : 7
source     :
    - https://download.kde.org/stable/qca/2.2.1/qca-2.2.1.tar.xz : d716d2d8e3ed8d95bbdb061f03081d7d032206f746a30a4d29d72196f50e7b02
license    : LGPL-2.1-only
component  : security.crypto
summary    : QCA is a library that provides an easy API for a range of cryptographic features
description: |
    QCA is a library that provides an easy API for a range of cryptographic features, including SSL/TLS, X.509 certificates, SASL, OpenPGP, smartcards, and much more.
builddeps  :
    - pkgconfig(Qt5Core)
replaces   :
    - devel : qca-qt5-devel
    - qca-qt5
setup      : |
    %cmake_ninja -DQCA_FEATURE_INSTALL_DIR=/usr/share/qt5/mkspecs/features \
                 -DQCA_LIBRARY_INSTALL_DIR=%libdir% \
                 -DQCA_PLUGINS_INSTALL_DIR=%libdir%/qca .
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
