name       : qca
version    : 2.1.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/qca/2.1.3/src/qca-2.1.3.tar.xz : 003fd86a32421057a03b18a8168db52e2940978f9db5ebbb6a08882f8ab1e353
license    : LGPL-2.1-only
component  : security.crypto
summary    : QCA is a library that provides an easy API for a range of cryptographic features
description: |
    QCA is a library that provides an easy API for a range of cryptographic features, including SSL/TLS, X.509 certificates, SASL, OpenPGP, smartcards, and much more.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(openssl)
replaces   :
    - devel : qca-qt5-devel
    - qca-qt5
setup      : |
    %cmake -DQCA_FEATURE_INSTALL_DIR=/usr/share/qt5/mkspecs/features \
           -DQCA_LIBRARY_INSTALL_DIR=%libdir% \
           -DQCA_PLUGINS_INSTALL_DIR=%libdir%/qca .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
