name       : qca
version    : 2.1.1
release    : 2
source     :
    - http://download.kde.org/stable/qca/2.1.1/src/qca-2.1.1.tar.xz : 95de3e7910b5f9ec7084169989c9d98bfb527e6a4865fe17269c3b24308be983
license    : LGPL-2.1
component  :
    - security.crypto
    - qt5 : security.crypto
    - qt5-devel : programming.devel
summary    : QCA is a library that provides an easy API for a range of cryptographic features
description: |
    QCA is a library that provides an easy API for a range of cryptographic features
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(Qt5Core)
    - pkgconfig(openssl)
rundeps    :
    - qt5-devel:
        qca-qt5
setup      : |
    mkdir build-qt4 && pushd build-qt4
        %cmake -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
               -DQCA_LIBRARY_INSTALL_DIR=%libdir% \
               -DQCA_FEATURE_INSTALL_DIR=/usr/share/qt4/mkspecs/features/ \
               -DQCA_PLUGINS_INSTALL_DIR=%libdir%/qca \
               -DQT4_BUILD=ON ..
    popd
    mkdir build-qt5 && pushd build-qt5
        %cmake -DQCA_FEATURE_INSTALL_DIR=/usr/share/qt5/mkspecs/features \
               -DQCA_LIBRARY_INSTALL_DIR=%libdir% \
               -DQCA_PLUGINS_INSTALL_DIR=%libdir%/qca-qt5 ..
build      : |
    pushd build-qt4
        %make
    popd
    pushd build-qt5
        %make
install    : |
    pushd build-qt4
        %make_install
    popd
    pushd build-qt5
        %make_install
patterns   :
    - qt5:
        - /usr/bin/*-qt5
        - /usr/lib64/libqca-qt5*
        - /usr/lib64/qca-qt5
        - /usr/share/man/man1/qcatool-qt5.1
        - /usr/share/qt5/mkspecs/features/crypto.prf
    - qt5-devel:
        - /usr/include/Qca-qt5
        - /usr/lib64/cmake/Qca-qt5
        - /usr/lib64/libqca-qt5.so
        - /usr/lib64/pkgconfig/qca2-qt5.pc
