name       : qca
version    : 2.1.0
release    : 1
source     :
    - http://delta.affinix.com/download/qca/2.0/qca-2.1.0.tar.gz : 226dcd76138c3738cdc15863607a96b3758a4c3efd3c47295939bcea4e7a9284
license    : LGPL-2.1
component  : security.crypto
summary    : QCA is a library that provides an easy API for a range of cryptographic features
description: |
    QCA is a library that provides an easy API for a range of cryptographic features
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(openssl)
setup      : |
    %cmake -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 .
build      : |
    %make
install    : |
    %make_install
